In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Calendar CSV

In [2]:
df_cal = pd.read_csv('../data/calendar.csv')

In [3]:
df_cal.head(50)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,172196,2019-06-29,f,$350.00,$350.00,3,21
1,360,2019-06-29,f,$127.00,$127.00,2,29
2,360,2019-06-30,f,$127.00,$127.00,1,29
3,360,2019-07-01,f,$127.00,$127.00,1,29
4,360,2019-07-02,f,$127.00,$127.00,1,29
5,360,2019-07-03,f,$127.00,$127.00,1,29
6,360,2019-07-04,f,$127.00,$127.00,1,29
7,360,2019-07-05,f,$127.00,$127.00,1,29
8,360,2019-07-06,f,$127.00,$127.00,2,29
9,360,2019-07-07,f,$127.00,$127.00,1,29
10,360,2019-07-08,f,$131.00,$131.00,1,29
11,360,2019-07-09,f,$136.00,$136.00,1,29
12,360,2019-07-10,t,$127.00,$127.00,1,29
13,360,2019-07-11,f,$127.00,$127.00,1,29
14,360,2019-07-12,f,$127.00,$127.00,1,29
15,360,2019-07-13,f,$127.00,$127.00,2,29
16,360,2019-07-14,f,$127.00,$127.00,1,29
17,360,2019-07-15,f,$127.00,$127.00,1,29
18,360,2019-07-16,t,$127.00,$127.00,1,29
19,360,2019-07-17,f,$127.00,$127.00,1,29
20,360,2019-07-18,f,$127.00,$127.00,1,29
21,360,2019-07-19,f,$127.00,$127.00,1,29
22,360,2019-07-20,f,$127.00,$127.00,2,29
23,360,2019-07-21,f,$150.00,$150.00,1,29
24,360,2019-07-22,f,$127.00,$127.00,1,29
25,360,2019-07-23,f,$127.00,$127.00,1,29
26,360,2019-07-24,t,$130.00,$130.00,1,29
27,360,2019-07-25,t,$127.00,$127.00,1,29
28,360,2019-07-26,f,$139.00,$139.00,1,29
29,360,2019-07-27,f,$139.00,$139.00,2,29
30,360,2019-07-28,t,$127.00,$127.00,1,29
31,360,2019-07-29,f,$127.00,$127.00,1,29
32,360,2019-07-30,f,$127.00,$127.00,1,29
33,360,2019-07-31,t,$127.00,$127.00,1,29
34,360,2019-08-01,f,$127.00,$127.00,1,29
35,360,2019-08-02,f,$127.00,$127.00,1,29
36,360,2019-08-03,f,$127.00,$127.00,2,29
37,360,2019-08-04,f,$127.00,$127.00,1,29
38,360,2019-08-05,t,$127.00,$127.00,1,29
39,360,2019-08-06,t,$127.00,$127.00,1,29
40,360,2019-08-07,f,$127.00,$127.00,1,29
41,360,2019-08-08,f,$127.00,$127.00,1,29
42,360,2019-08-09,f,$127.00,$127.00,1,29
43,360,2019-08-10,f,$127.00,$127.00,2,29
44,360,2019-08-11,t,$127.00,$127.00,1,29
45,360,2019-08-12,t,$127.00,$127.00,1,29
46,360,2019-08-13,f,$127.00,$127.00,1,29
47,360,2019-08-14,t,$127.00,$127.00,1,29
48,360,2019-08-15,f,$127.00,$127.00,1,29
49,360,2019-08-16,f,$127.00,$127.00,1,29

In [4]:
df_cal.tail(20)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
1646495,35606018,2020-06-08,f,$174.00,$174.00,1,7
1646496,35606018,2020-06-09,f,$164.00,$164.00,1,7
1646497,35606018,2020-06-10,f,$186.00,$186.00,1,7
1646498,35606018,2020-06-11,f,$244.00,$244.00,1,7
1646499,35606018,2020-06-12,f,$300.00,$300.00,1,7
1646500,35606018,2020-06-13,f,$310.00,$310.00,2,7
1646501,35606018,2020-06-14,f,$224.00,$224.00,1,7
1646502,35606018,2020-06-15,f,$176.00,$176.00,1,7
1646503,35606018,2020-06-16,f,$164.00,$164.00,1,7
1646504,35606018,2020-06-17,f,$186.00,$186.00,1,7
1646505,35606018,2020-06-18,f,$246.00,$246.00,1,7
1646506,35606018,2020-06-19,f,$302.00,$302.00,1,7
1646507,35606018,2020-06-20,f,$314.00,$314.00,2,7
1646508,35606018,2020-06-21,f,$226.00,$226.00,1,7
1646509,35606018,2020-06-22,f,$178.00,$178.00,1,7
1646510,35606018,2020-06-23,f,$166.00,$166.00,1,7
1646511,35606018,2020-06-24,f,$188.00,$188.00,1,7
1646512,35606018,2020-06-25,f,$248.00,$248.00,1,7
1646513,35606018,2020-06-26,f,$304.00,$304.00,1,7
1646514,35606018,2020-06-27,f,$316.00,$316.00,2,7

In [5]:
df_cal.columns

Index(['listing_id', 'date', 'available', 'price', 'adjusted_price',
       'minimum_nights', 'maximum_nights'],
      dtype='object')

In [6]:
# Checking to make sure the dates are consectuive

df_cal['date'].unique()

array(['2019-06-29', '2019-06-30', '2019-07-01', '2019-07-02',
       '2019-07-03', '2019-07-04', '2019-07-05', '2019-07-06',
       '2019-07-07', '2019-07-08', '2019-07-09', '2019-07-10',
       '2019-07-11', '2019-07-12', '2019-07-13', '2019-07-14',
       '2019-07-15', '2019-07-16', '2019-07-17', '2019-07-18',
       '2019-07-19', '2019-07-20', '2019-07-21', '2019-07-22',
       '2019-07-23', '2019-07-24', '2019-07-25', '2019-07-26',
       '2019-07-27', '2019-07-28', '2019-07-29', '2019-07-30',
       '2019-07-31', '2019-08-01', '2019-08-02', '2019-08-03',
       '2019-08-04', '2019-08-05', '2019-08-06', '2019-08-07',
       '2019-08-08', '2019-08-09', '2019-08-10', '2019-08-11',
       '2019-08-12', '2019-08-13', '2019-08-14', '2019-08-15',
       '2019-08-16', '2019-08-17', '2019-08-18', '2019-08-19',
       '2019-08-20', '2019-08-21', '2019-08-22', '2019-08-23',
       '2019-08-24', '2019-08-25', '2019-08-26', '2019-08-27',
       '2019-08-28', '2019-08-29', '2019-08-30', '2019-08-31',
       '2019-09-01', '2019-09-02', '2019-09-03', '2019-09-04',
       '2019-09-05', '2019-09-06', '2019-09-07', '2019-09-08',
       '2019-09-09', '2019-09-10', '2019-09-11', '2019-09-12',
       '2019-09-13', '2019-09-14', '2019-09-15', '2019-09-16',
       '2019-09-17', '2019-09-18', '2019-09-19', '2019-09-20',
       '2019-09-21', '2019-09-22', '2019-09-23', '2019-09-24',
       '2019-09-25', '2019-09-26', '2019-09-27', '2019-09-28',
       '2019-09-29', '2019-09-30', '2019-10-01', '2019-10-02',
       '2019-10-03', '2019-10-04', '2019-10-05', '2019-10-06',
       '2019-10-07', '2019-10-08', '2019-10-09', '2019-10-10',
       '2019-10-11', '2019-10-12', '2019-10-13', '2019-10-14',
       '2019-10-15', '2019-10-16', '2019-10-17', '2019-10-18',
       '2019-10-19', '2019-10-20', '2019-10-21', '2019-10-22',
       '2019-10-23', '2019-10-24', '2019-10-25', '2019-10-26',
       '2019-10-27', '2019-10-28', '2019-10-29', '2019-10-30',
       '2019-10-31', '2019-11-01', '2019-11-02', '2019-11-03',
       '2019-11-04', '2019-11-05', '2019-11-06', '2019-11-07',
       '2019-11-08', '2019-11-09', '2019-11-10', '2019-11-11',
       '2019-11-12', '2019-11-13', '2019-11-14', '2019-11-15',
       '2019-11-16', '2019-11-17', '2019-11-18', '2019-11-19',
       '2019-11-20', '2019-11-21', '2019-11-22', '2019-11-23',
       '2019-11-24', '2019-11-25', '2019-11-26', '2019-11-27',
       '2019-11-28', '2019-11-29', '2019-11-30', '2019-12-01',
       '2019-12-02', '2019-12-03', '2019-12-04', '2019-12-05',
       '2019-12-06', '2019-12-07', '2019-12-08', '2019-12-09',
       '2019-12-10', '2019-12-11', '2019-12-12', '2019-12-13',
       '2019-12-14', '2019-12-15', '2019-12-16', '2019-12-17',
       '2019-12-18', '2019-12-19', '2019-12-20', '2019-12-21',
       '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
       '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
       '2019-12-30', '2019-12-31', '2020-01-01', '2020-01-02',
       '2020-01-03', '2020-01-04', '2020-01-05', '2020-01-06',
       '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
       '2020-01-11', '2020-01-12', '2020-01-13', '2020-01-14',
       '2020-01-15', '2020-01-16', '2020-01-17', '2020-01-18',
       '2020-01-19', '2020-01-20', '2020-01-21', '2020-01-22',
       '2020-01-23', '2020-01-24', '2020-01-25', '2020-01-26',
       '2020-01-27', '2020-01-28', '2020-01-29', '2020-01-30',
       '2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03',
       '2020-02-04', '2020-02-05', '2020-02-06', '2020-02-07',
       '2020-02-08', '2020-02-09', '2020-02-10', '2020-02-11',
       '2020-02-12', '2020-02-13', '2020-02-14', '2020-02-15',
       '2020-02-16', '2020-02-17', '2020-02-18', '2020-02-19',
       '2020-02-20', '2020-02-21', '2020-02-22', '2020-02-23',
       '2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
       '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
       '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06',
       '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10',
       '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14',
       '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18',
       '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22',
       '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26',
       '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
       '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03',
       '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07',
       '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11',
       '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15',
       '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19',
       '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23',
       '2020-04-24', '2020-04-25', '2020-04-26', '2020-04-27',
       '2020-04-28', '2020-04-29', '2020-04-30', '2020-05-01',
       '2020-05-02', '2020-05-03', '2020-05-04', '2020-05-05',
       '2020-05-06', '2020-05-07', '2020-05-08', '2020-05-09',
       '2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13',
       '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17',
       '2020-05-18', '2020-05-19', '2020-05-20', '2020-05-21',
       '2020-05-22', '2020-05-23', '2020-05-24', '2020-05-25',
       '2020-05-26', '2020-05-27', '2020-05-28', '2020-05-29',
       '2020-05-30', '2020-05-31', '2020-06-01', '2020-06-02',
       '2020-06-03', '2020-06-04', '2020-06-05', '2020-06-06',
       '2020-06-07', '2020-06-08', '2020-06-09', '2020-06-10',
       '2020-06-11', '2020-06-12', '2020-06-13', '2020-06-14',
       '2020-06-15', '2020-06-16', '2020-06-17', '2020-06-18',
       '2020-06-19', '2020-06-20', '2020-06-21', '2020-06-22',
       '2020-06-23', '2020-06-24', '2020-06-25', '2020-06-26',
       '2020-06-27'], dtype=object)

In [7]:
# Found one of our listings! 

df_cal.loc[df_cal['listing_id'] == 23453925]

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
899700,23453925,2019-06-29,f,$46.00,$46.00,1,7
899701,23453925,2019-06-30,f,$44.00,$44.00,1,7
899702,23453925,2019-07-01,f,$44.00,$44.00,1,7
899703,23453925,2019-07-02,f,$45.00,$45.00,1,7
899704,23453925,2019-07-03,f,$44.00,$44.00,1,7
899705,23453925,2019-07-04,f,$46.00,$46.00,1,7
899706,23453925,2019-07-05,f,$46.00,$46.00,1,7
899707,23453925,2019-07-06,f,$46.00,$46.00,1,7
899708,23453925,2019-07-07,f,$46.00,$46.00,1,7
899709,23453925,2019-07-08,f,$44.00,$44.00,1,7
899710,23453925,2019-07-09,f,$46.00,$46.00,1,7
899711,23453925,2019-07-10,f,$46.00,$46.00,1,7
899712,23453925,2019-07-11,f,$46.00,$46.00,1,7
899713,23453925,2019-07-12,f,$46.00,$46.00,1,7
899714,23453925,2019-07-13,f,$47.00,$47.00,1,7
899715,23453925,2019-07-14,f,$44.00,$44.00,1,7
899716,23453925,2019-07-15,f,$44.00,$44.00,1,7
899717,23453925,2019-07-16,f,$44.00,$44.00,1,7
899718,23453925,2019-07-17,f,$45.00,$45.00,1,7
899719,23453925,2019-07-18,f,$46.00,$46.00,1,7
899720,23453925,2019-07-19,f,$46.00,$46.00,1,7
899721,23453925,2019-07-20,f,$46.00,$46.00,1,7
899722,23453925,2019-07-21,t,$46.00,$46.00,1,7
899723,23453925,2019-07-22,t,$46.00,$46.00,1,7
899724,23453925,2019-07-23,t,$46.00,$46.00,1,7
899725,23453925,2019-07-24,t,$46.00,$46.00,1,7
899726,23453925,2019-07-25,t,$46.00,$46.00,1,7
899727,23453925,2019-07-26,f,$49.00,$49.00,1,7
899728,23453925,2019-07-27,f,$50.00,$50.00,1,7
899729,23453925,2019-07-28,f,$49.00,$49.00,1,7
...,...,...,...,...,...,...,...
900418,23453925,2020-05-29,f,$82.00,$82.00,1,7
900419,23453925,2020-05-30,f,$82.00,$82.00,1,7
900420,23453925,2020-05-31,f,$82.00,$82.00,1,7
900421,23453925,2020-06-01,f,$82.00,$82.00,1,7
900422,23453925,2020-06-02,f,$82.00,$82.00,1,7
900423,23453925,2020-06-03,f,$82.00,$82.00,1,7
900424,23453925,2020-06-04,f,$82.00,$82.00,1,7
900425,23453925,2020-06-05,f,$82.00,$82.00,1,7
900426,23453925,2020-06-06,f,$82.00,$82.00,1,7
900427,23453925,2020-06-07,f,$82.00,$82.00,1,7
900428,23453925,2020-06-08,f,$82.00,$82.00,1,7
900429,23453925,2020-06-09,f,$82.00,$82.00,1,7
900430,23453925,2020-06-10,f,$82.00,$82.00,1,7
900431,23453925,2020-06-11,f,$82.00,$82.00,1,7
900432,23453925,2020-06-12,f,$82.00,$82.00,1,7
900433,23453925,2020-06-13,f,$82.00,$82.00,1,7
900434,23453925,2020-06-14,f,$82.00,$82.00,1,7
900435,23453925,2020-06-15,f,$82.00,$82.00,1,7
900436,23453925,2020-06-16,f,$82.00,$82.00,1,7
900437,23453925,2020-06-17,f,$82.00,$82.00,1,7
900438,23453925,2020-06-18,f,$82.00,$82.00,1,7
900439,23453925,2020-06-19,f,$82.00,$82.00,1,7
900440,23453925,2020-06-20,f,$82.00,$82.00,1,7
900441,23453925,2020-06-21,f,$82.00,$82.00,1,7
900442,23453925,2020-06-22,f,$82.00,$82.00,1,7
900443,23453925,2020-06-23,f,$82.00,$82.00,1,7
900444,23453925,2020-06-24,f,$82.00,$82.00,1,7
900445,23453925,2020-06-25,f,$82.00,$82.00,1,7
900446,23453925,2020-06-26,f,$82.00,$82.00,1,7
900447,23453925,2020-06-27,f,$82.00,$82.00,1,7

In [8]:
# And our other listing! 
df_cal.loc[df_cal['listing_id'] == 25232441]

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
941237,25232441,2019-06-29,f,$47.00,$47.00,1,7
941238,25232441,2019-06-30,f,$47.00,$47.00,1,7
941239,25232441,2019-07-01,f,$47.00,$47.00,1,7
941240,25232441,2019-07-02,f,$48.00,$48.00,1,7
941241,25232441,2019-07-03,f,$47.00,$47.00,1,7
941242,25232441,2019-07-04,f,$47.00,$47.00,1,7
941243,25232441,2019-07-05,f,$49.00,$49.00,1,7
941244,25232441,2019-07-06,f,$49.00,$49.00,1,7
941245,25232441,2019-07-07,f,$48.00,$48.00,1,7
941246,25232441,2019-07-08,f,$48.00,$48.00,1,7
941247,25232441,2019-07-09,f,$47.00,$47.00,1,7
941248,25232441,2019-07-10,f,$48.00,$48.00,1,7
941249,25232441,2019-07-11,f,$49.00,$49.00,1,7
941250,25232441,2019-07-12,f,$49.00,$49.00,1,7
941251,25232441,2019-07-13,f,$48.00,$48.00,1,7
941252,25232441,2019-07-14,f,$47.00,$47.00,1,7
941253,25232441,2019-07-15,f,$47.00,$47.00,1,7
941254,25232441,2019-07-16,f,$47.00,$47.00,1,7
941255,25232441,2019-07-17,f,$46.00,$46.00,1,7
941256,25232441,2019-07-18,f,$45.00,$45.00,1,7
941257,25232441,2019-07-19,f,$55.00,$55.00,1,7
941258,25232441,2019-07-20,f,$54.00,$54.00,1,7
941259,25232441,2019-07-21,f,$54.00,$54.00,1,7
941260,25232441,2019-07-22,f,$53.00,$53.00,1,7
941261,25232441,2019-07-23,f,$54.00,$54.00,1,7
941262,25232441,2019-07-24,t,$47.00,$47.00,1,7
941263,25232441,2019-07-25,f,$54.00,$54.00,1,7
941264,25232441,2019-07-26,f,$55.00,$55.00,1,7
941265,25232441,2019-07-27,f,$56.00,$56.00,1,7
941266,25232441,2019-07-28,f,$54.00,$54.00,1,7
...,...,...,...,...,...,...,...
941671,25232441,2020-05-29,f,$82.00,$82.00,1,7
941672,25232441,2020-05-30,f,$82.00,$82.00,1,7
941673,25232441,2020-05-31,f,$82.00,$82.00,1,7
941674,25232441,2020-06-01,f,$82.00,$82.00,1,7
941675,25232441,2020-06-02,f,$82.00,$82.00,1,7
941676,25232441,2020-06-03,f,$82.00,$82.00,1,7
941677,25232441,2020-06-04,f,$82.00,$82.00,1,7
941678,25232441,2020-06-05,f,$82.00,$82.00,1,7
941679,25232441,2020-06-06,f,$82.00,$82.00,1,7
941680,25232441,2020-06-07,f,$82.00,$82.00,1,7
941681,25232441,2020-06-08,f,$82.00,$82.00,1,7
941682,25232441,2020-06-09,f,$82.00,$82.00,1,7
941683,25232441,2020-06-10,f,$82.00,$82.00,1,7
941684,25232441,2020-06-11,f,$82.00,$82.00,1,7
941685,25232441,2020-06-12,f,$82.00,$82.00,1,7
941686,25232441,2020-06-13,f,$82.00,$82.00,1,7
941687,25232441,2020-06-14,f,$82.00,$82.00,1,7
941688,25232441,2020-06-15,f,$82.00,$82.00,1,7
941689,25232441,2020-06-16,f,$82.00,$82.00,1,7
941690,25232441,2020-06-17,f,$82.00,$82.00,1,7
941691,25232441,2020-06-18,f,$82.00,$82.00,1,7
941692,25232441,2020-06-19,f,$82.00,$82.00,1,7
941693,25232441,2020-06-20,f,$82.00,$82.00,1,7
941694,25232441,2020-06-21,f,$82.00,$82.00,1,7
941695,25232441,2020-06-22,f,$82.00,$82.00,1,7
941696,25232441,2020-06-23,f,$82.00,$82.00,1,7
941697,25232441,2020-06-24,f,$82.00,$82.00,1,7
941698,25232441,2020-06-25,f,$82.00,$82.00,1,7
941699,25232441,2020-06-26,f,$82.00,$82.00,1,7
941700,25232441,2020-06-27,f,$82.00,$82.00,1,7

In [9]:
# Seeing which columns need to be converted 

df_cal.dtypes

listing_id         int64
date              object
available         object
price             object
adjusted_price    object
minimum_nights     int64
maximum_nights     int64
dtype: object

In [10]:
df_cal.loc[df_cal['date'] == '2020-06-01']

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
352,360,2020-06-01,t,$153.00,$153.00,1,29
898,172196,2020-06-01,t,$434.00,$434.00,3,21
1069,364,2020-06-01,t,$179.00,$179.00,185,190
1558,590,2020-06-01,f,$67.00,$67.00,1,300
2030,592,2020-06-01,f,$42.00,$42.00,30,365
2163,177942,2020-06-01,f,$213.00,$213.00,2,1825
2587,686,2020-06-01,t,$75.00,$75.00,2,180
3239,1940,2020-06-01,f,$104.00,$104.00,2,120
3580,1678845,2020-06-01,t,$120.00,$120.00,2,1125
3835,184529,2020-06-01,t,$35.00,$35.00,30,360
4110,2086,2020-06-01,t,$81.00,$81.00,180,1125
4501,1724186,2020-06-01,f,$83.00,$83.00,2,50
5019,21745,2020-06-01,t,$70.00,$70.00,2,180
5191,1733052,2020-06-01,t,$80.00,$80.00,1,30
6067,192430,2020-06-01,f,$32.00,$32.00,14,90
6101,31503,2020-06-01,t,$119.00,$119.00,3,730
6466,39405,2020-06-01,t,$119.00,$119.00,1,29
6544,1737365,2020-06-01,t,$136.00,$136.00,29,1124
6909,1785877,2020-06-01,t,$56.00,$56.00,2,1125
7274,1792152,2020-06-01,t,$83.00,$83.00,2,1125
7652,1801950,2020-06-01,f,$268.00,$268.00,2,1125
7999,56185,2020-06-01,t,$300.00,$300.00,3,365
8457,1813896,2020-06-01,f,$62.00,$62.00,2,5
8791,59631,2020-06-01,t,$190.00,$190.00,1,1125
9156,217715,2020-06-01,t,$89.00,$89.00,1,5
9882,74125,2020-06-01,f,$120.00,$120.00,3,1124
10345,1891877,2020-06-01,f,$54.00,$54.00,2,90
10700,81540,2020-06-01,t,$80.00,$80.00,3,120
10928,1900638,2020-06-01,f,$29.00,$29.00,5,28
10971,217996,2020-06-01,t,$66.00,$66.00,30,180
...,...,...,...,...,...,...,...
1636134,35489830,2020-06-01,f,$35.00,$35.00,5,1125
1636269,34788647,2020-06-01,t,$50.00,$50.00,1,1125
1636634,35200831,2020-06-01,t,$27.00,$27.00,1,30
1636999,36105706,2020-06-01,f,$100.00,$100.00,1,1125
1637470,35493196,2020-06-01,t,$53.00,$53.00,1,1125
1638050,35203788,2020-06-01,t,$25.00,$25.00,1,1
1638522,35465347,2020-06-01,f,$78.00,$78.00,1,1125
1638672,35494910,2020-06-01,f,$32.00,$32.00,3,60
1639038,35382150,2020-06-01,t,$24.00,$24.00,1,30
1639189,35969596,2020-06-01,f,$110.00,$110.00,1,1125
1639775,30705290,2020-06-01,f,$50.00,$50.00,2,30
1640135,35509441,2020-06-01,t,$154.00,$154.00,2,1125
1640284,35198043,2020-06-01,t,$26.00,$26.00,1,30
1640648,35511163,2020-06-01,f,$205.00,$205.00,1,2
1641013,35516217,2020-06-01,f,$125.00,$125.00,1,1125
1641378,35518196,2020-06-01,f,$40.00,$40.00,1,15
1641743,35518521,2020-06-01,t,$493.00,$493.00,3,1125
1642108,35520755,2020-06-01,f,$85.00,$85.00,1,29
1642473,35534264,2020-06-01,f,$90.00,$90.00,90,1125
1642838,35535425,2020-06-01,t,$222.00,$222.00,2,1125
1643203,35538823,2020-06-01,t,$222.00,$222.00,2,1125
1643568,35544358,2020-06-01,f,$48.00,$48.00,2,1125
1643933,35549118,2020-06-01,f,$85.00,$85.00,1,9
1644298,35565273,2020-06-01,f,$112.00,$112.00,2,365
1644663,35570877,2020-06-01,f,$137.00,$137.00,1,7
1645028,35575152,2020-06-01,f,$107.00,$107.00,2,4
1645393,35578815,2020-06-01,f,$258.00,$258.00,1,7
1645758,35579238,2020-06-01,f,$175.00,$175.00,2,15
1646123,35605994,2020-06-01,f,$225.00,$225.00,1,7
1646488,35606018,2020-06-01,f,$218.00,$218.00,1,7

In [11]:
df_cal.shape

(1646515, 7)

# Listing CSV

In [12]:
df_lst = pd.read_csv('../data/listings.csv')

In [13]:
df_lst.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,360,https://www.airbnb.com/rooms/360,20190629051303,2019-06-29,LoHi Secret garden at the Chickadee Cottage,Come enjoy our oasis is the city and stay at o...,Chickadee Cottage is the largest of our guest ...,Come enjoy our oasis is the city and stay at o...,none,those who are interested in our local brews - ...,...,t,f,moderate,t,t,3,3,0,0,5.51
1,364,https://www.airbnb.com/rooms/364,20190629051303,2019-06-29,Lodo / RiNo LOFT via airport train,"Modern 1,000 square foot loft in the heart of ...","BRAND NEW FOR 2016 - April 22, 2016 - the air...","Modern 1,000 square foot loft in the heart of ...",none,"Ten brewpubs within walking distance, two grea...",...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,0.71
2,590,https://www.airbnb.com/rooms/590,20190629051303,2019-06-29,Comfortable - and a great value!,"Large guest room in my home, where I also live...",I have been enjoying welcoming many wonderful ...,"Large guest room in my home, where I also live...",none,I love the diversity of my neighborhood and it...,...,f,f,flexible,f,f,2,0,2,0,4.57
3,592,https://www.airbnb.com/rooms/592,20190629051303,2019-06-29,private,This room is in the basement. It does not hav...,This is a basement room. You can sometimes he...,This room is in the basement. It does not hav...,none,NaN,...,f,f,flexible,f,f,2,0,2,0,1.38
4,686,https://www.airbnb.com/rooms/686,20190629051303,2019-06-29,Alexandra's Uptown Queen Bed Room,Thank you for visiting my Queen Bed Room site!...,Thank you for checking out my Bed and Breakfas...,Thank you for visiting my Queen Bed Room site!...,none,"I love my Uptown neighborhood, which is within...",...,t,f,moderate,f,f,2,0,2,0,4.70

In [14]:
df_lst.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

In [15]:
df_lst.dtypes

id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
name                                             object
summary                                          object
space                                            object
description                                      object
experiences_offered                              object
neighborhood_overview                            object
notes                                            object
transit                                          object
access                                           object
interaction                                      object
house_rules                                      object
thumbnail_url                                   float64
medium_url                                      float64
picture_url                                      object
xl_picture_url                                  float64
host_id                                           int64
host_url                                         object
host_name                                        object
host_since                                       object
host_location                                    object
host_about                                       object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                            float64
host_is_superhost                                object
host_thumbnail_url                               object
                                                 ...
has_availability                                 object
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                            object
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
first_review                                     object
last_review                                      object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
requires_license                                 object
license                                          object
jurisdiction_names                               object
instant_bookable                                 object
is_business_travel_ready                         object
cancellation_policy                              object
require_guest_profile_picture                    object
require_guest_phone_verification                 object
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 106, dtype: object

In [16]:
col = df_lst.columns.tolist()
col

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'thumbnail_url',
 'medium_url',
 'picture_url',
 'xl_picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'latitude',
 'longitude',
 'is_location_exact',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'bed_type',
 'amenities',
 'square_feet',
 'price',
 'weekly_price',
 'monthly_price',
 'security_deposit',
 'cleaning_fee',
 'guests_included',
 'extra_people',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'jurisdiction_names',
 'instant_bookable',
 'is_business_travel_ready',
 'cancellation_policy',
 'require_guest_profile_picture',
 'require_guest_phone_verification',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [17]:
df_lst['neighbourhood_cleansed'].unique().tolist()

['Highland',
 'Five Points',
 'North Park Hill',
 'North Capitol Hill',
 'Baker',
 'Hale',
 'West Highland',
 'Capitol Hill',
 'Overland',
 'City Park',
 'Washington Park',
 'Union Station',
 'South Park Hill',
 'University Park',
 'Washington Park West',
 'Clayton',
 'City Park West',
 'Berkeley',
 'Stapleton',
 'Jefferson Park',
 'Lowry Field',
 'Platt Park',
 'Sunnyside',
 'Congress Park',
 'Goldsmith',
 'Sloan Lake',
 'Barnum',
 'Speer',
 'CBD',
 'Lincoln Park',
 'Cole',
 'Cheesman Park',
 'University',
 'Washington Virginia Vale',
 'West Colfax',
 'Cory - Merrill',
 'Whittier',
 'Montclair',
 'Hilltop',
 'Skyland',
 'Country Club',
 'Villa Park',
 'Athmar Park',
 'Fort Logan',
 'Windsor',
 'Gateway - Green Valley Ranch',
 'Indian Creek',
 'Rosedale',
 'Bear Valley',
 'Barnum West',
 'Cherry Creek',
 'Harvey Park',
 'Ruby Hill',
 'Hampden South',
 'Civic Center',
 'Northeast Park Hill',
 'Harvey Park South',
 'Regis',
 'College View - South Platte',
 'Chaffee Park',
 'Virginia Village',
 'Hampden',
 'Southmoor Park',
 'Belcaro',
 'University Hills',
 'East Colfax',
 'Elyria Swansea',
 'Marston',
 'Montbello',
 'Globeville',
 'Mar Lee',
 'Valverde',
 'DIA',
 'Kennedy',
 'Westwood',
 'Auraria',
 'Wellshire',
 'Sun Valley']

In [18]:
# Checking out how long notes might be and if it's something I want to include when cleaning
# the data

df_lst['notes'].iloc[150]

"DENVER SHORT TERM LICENSE # (Phone number hidden by Airbnb) BFN (Phone number hidden by Airbnb) It's perfectly charming, beautiful and bright..... with a super location to boot.  Easy access to downtown Denver, the State Capital, 16th Street Mall, Convention Center, Pepsi Center, Sports Authority Field, Coors Field and Cherry Creek Mall. Our home is  located in Capital Hill, Denver,  voted one of the 10 most beautiful neighborhoods in the US.  This neighborhood is electric and colorful and one of the most vibrant and convenient locations in all of Denver, with a walk score of 96, which is a walkers paradise.   Markets.....Natural Grocers is 5 blocks away, King Scoopers is 8 blocks away as is Trader Joe's........ Safeway is approximately 9 blocks.  Located on historic Pearl St. the home is modern and fun. Attractions are also a short walk.... (5 blocks) to the State Capital building and 16th Street Mall (6 blocks) puts you in the middle of downtown. ….less than 3 miles from any of Denve"

In [19]:
df_lst['property_type'].unique()

array(['Guesthouse', 'Loft', 'House', 'Apartment', 'Bed and breakfast',
       'Guest suite', 'Cottage', 'Townhouse', 'Condominium', 'Bungalow',
       'Serviced apartment', 'Tiny house', 'Castle', 'Other', 'Hostel',
       'Villa', 'Camper/RV', 'Tent', 'Campsite'], dtype=object)

In [20]:
df_lst['room_type'].unique()

array(['Entire home/apt', 'Private room', 'Shared room'], dtype=object)

In [21]:
# Can see who has their license number on their listing and who does not

df_lst['license'].head()

0    2017-BFN-0002177
1                 NaN
2    2018-BFN-O0O5791
3    2018-BFN-O0O5791
4    2016-BFN-0008368
Name: license, dtype: object

In [22]:
df_lst.shape

(4511, 106)

# Review CSV

In [23]:
df_rev = pd.read_csv('../data/reviews.csv')

In [24]:
df_rev.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,360,307152490,2018-08-13,46723582,Madeleine,"This space was perfect! Great location, hosts,..."
1,360,311601388,2018-08-21,68751664,Janelle,Hidden Gem in Denver. Magical Secret garden ce...
2,360,312497032,2018-08-23,57773484,Ziad,Amazing stay at one of the best kept AirBnB se...
3,360,313089933,2018-08-24,11982181,Andrea,The cottage has a great setting with a garden ...
4,360,314492150,2018-08-26,14620568,Iris,"Super cute place, very peaceful (loved the gar..."

In [25]:
df_rev.columns

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')

In [26]:
df_rev.dtypes

listing_id        int64
id                int64
date             object
reviewer_id       int64
reviewer_name    object
comments         object
dtype: object

In [27]:
df_rev.shape

(221847, 6)